remote_theme: carlosperate/jekyll-theme-rtd
title: Bachata Musicality

site_author: Stuart Paton
repo_url: 'https://github.com/patons02/bachata-musicality'
edit_on_github: true
github_docs_folder: false
sticky_navigation: true
prev_next_buttons_location: None
prev_next_buttons_location: top
prev_next_buttons_location: bottom
prev_next_buttons_location: both
search_enabled: true
# The highlight.js library provides 79 different colours for their syntax highlighting. The default is github-gist.
hljs_style: github-gist